### ISSUE TITLE
上传文件报错

### ISSUE THREAD

**Issue by auqhjjqdo** [foyoux/aligo#127]
**操作系统信息**
所有平台

**错误描述**
```
Traceback (most recent call last):
  File "***\***.py", line 30, in <module>
    aligo.upload_file(
  File "***\venv\lib\site-packages\aligo\core\Create.py", line 233, in upload_file
    part_info = self._pre_hash(file_path=file_path, file_size=file_size, name=name,
  File "***\venv\lib\site-packages\aligo\core\Create.py", line 71, in _pre_hash
    body = CreateFileRequest(
  File "***\venv\lib\site-packages\datclass\__init__.py", line 42, in __datclass_init__
    getattr(obj, _ORIGINAL_INIT)(*args, **{k: kwargs.pop(k) for k in obj.__dataclass_fields__ if k in kwargs})
  File "<string>", line 25, in __init__
  File "***\venv\lib\site-packages\aligo\request\CreateFileRequest.py", line 36, in __post_init__
    super().__post_init__()
  File "***\venv\lib\site-packages\datclass\__init__.py", line 74, in __post_init__
    setattr(self, attr_name, [item_type(**i) for i in getattr(self, attr_name) or []])
  File "***\venv\lib\site-packages\datclass\__init__.py", line 74, in <listcomp>
    setattr(self, attr_name, [item_type(**i) for i in getattr(self, attr_name) or []])
TypeError: aligo.types.UploadPartInfo.UploadPartInfo() argument after ** must be a mapping, not UploadPartInfo
```

**Comment by lemisky** [comment]
收到，马上处理

**Comment by lemisky** [comment]
@auqhjjqdo 请升级 **datclass** 库

```sh
pip install -U datclass
```
