### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by gitstq** [foyoux/aligo#146]
pip install --upgrade aligo
Collecting aligo
  Using cached aligo-6.1.8-py3-none-any.whl.metadata (7.4 kB)
Collecting datclass>=0.2.21 (from aligo)
  Using cached datclass-0.2.25-py3-none-any.whl.metadata (4.8 kB)
Requirement already satisfied: requests>=2.9.0 in /usr/local/lib/python3.9/dist-packages (from aligo) (2.31.0)
Collecting qrcode[pil] (from aligo)
  Using cached qrcode-7.4.2-py3-none-any.whl (46 kB)
Collecting coloredlogs (from aligo)
  Using cached coloredlogs-15.0.1-py2.py3-none-any.whl (46 kB)
Collecting tqdm>=4.50.0 (from aligo)
  Using cached tqdm-4.66.1-py3-none-any.whl.metadata (57 kB)
Collecting qrcode-terminal (from aligo)
  Using cached qrcode_terminal-0.8-py3-none-any.whl
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.9/dist-packages (from requests>=2.9.0->aligo) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.9/dist-packages (from requests>=2.9.0->aligo) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.9/dist-packages (from requests>=2.9.0->aligo) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.9/dist-packages (from requests>=2.9.0->aligo) (2023.7.22)
Collecting humanfriendly>=9.1 (from coloredlogs->aligo)
  Using cached humanfriendly-10.0-py2.py3-none-any.whl (86 kB)
Collecting Pillow (from qrcode-terminal->aligo)
  Using cached Pillow-10.1.0.tar.gz (50.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting typing-extensions (from qrcode[pil]->aligo)
  Using cached typing_extensions-4.8.0-py3-none-any.whl.metadata (3.0 kB)
Collecting pypng (from qrcode[pil]->aligo)
  Using cached pypng-0.20220715.0-py3-none-any.whl (58 kB)
Using cached aligo-6.1.8-py3-none-any.whl (138 kB)
Using cached datclass-0.2.25-py3-none-any.whl (12 kB)
Using cached tqdm-4.66.1-py3-none-any.whl (78 kB)
Using cached typing_extensions-4.8.0-py3-none-any.whl (31 kB)
Building wheels for collected packages: Pillow
  Building wheel for Pillow (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for Pillow (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [199 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-armv7l-cpython-39
      creating build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/TiffTags.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/__main__.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/CurImagePlugin.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/ImageCms.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/WalImageFile.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/PpmImagePlugin.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/MspImagePlugin.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/PaletteFile.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/_deprecate.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/ImageTk.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/_binary.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/GimpGradientFile.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/_version.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/XVThumbImagePlugin.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/BdfFontFile.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/PngImagePlugin.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/PyAccess.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/MpegImagePlugin.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/DdsImagePlugin.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/WebPImagePlugin.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/ImageMorph.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/ImageFilter.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/FpxImagePlugin.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/GdImageFile.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/ImImagePlugin.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/XpmImagePlugin.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/ImageQt.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/PSDraw.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/PalmImagePlugin.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/PdfParser.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/ImageStat.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/Image.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/PcdImagePlugin.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/SgiImagePlugin.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/McIdasImagePlugin.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/ImageMode.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/TarIO.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/ImageEnhance.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/ImageOps.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/FliImagePlugin.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/FitsImagePlugin.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/__init__.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/ImageShow.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/JpegPresets.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/PsdImagePlugin.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/PcxImagePlugin.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/MicImagePlugin.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/BlpImagePlugin.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/IptcImagePlugin.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/PcfFontFile.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/ImtImagePlugin.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/ImageFont.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/WmfImagePlugin.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/ImageMath.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/ImageDraw.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/XbmImagePlugin.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/SunImagePlugin.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/Hdf5StubImagePlugin.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/FontFile.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/TiffImagePlugin.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/_tkinter_finder.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/BmpImagePlugin.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/FtexImagePlugin.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/EpsImagePlugin.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/TgaImagePlugin.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/ImageSequence.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/ImageWin.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/ContainerIO.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/DcxImagePlugin.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/ExifTags.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/PixarImagePlugin.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/GimpPaletteFile.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/ImagePath.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/ImageChops.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/GbrImagePlugin.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/IcnsImagePlugin.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/ImageColor.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/JpegImagePlugin.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/ImageTransform.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/ImagePalette.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/SpiderImagePlugin.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/IcoImagePlugin.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/ImageDraw2.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/features.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/MpoImagePlugin.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/GribStubImagePlugin.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/ImageGrab.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/_util.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/BufrStubImagePlugin.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/ImageFile.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/QoiImagePlugin.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/Jpeg2KImagePlugin.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/PdfImagePlugin.py -> build/lib.linux-armv7l-cpython-39/PIL
      copying src/PIL/GifImagePlugin.py -> build/lib.linux-armv7l-cpython-39/PIL
      running egg_info
      writing src/Pillow.egg-info/PKG-INFO
      writing dependency_links to src/Pillow.egg-info/dependency_links.txt
      writing requirements to src/Pillow.egg-info/requires.txt
      writing top-level names to src/Pillow.egg-info/top_level.txt
      reading manifest file 'src/Pillow.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching '*.c'
      warning: no files found matching '*.h'
      warning: no files found matching '*.sh'
      warning: no files found matching '*.txt'
      warning: no previously-included files found matching '.appveyor.yml'
      warning: no previously-included files found matching '.clang-format'
      warning: no previously-included files found matching '.coveragerc'
      warning: no previously-included files found matching '.editorconfig'
      warning: no previously-included files found matching '.readthedocs.yml'
      warning: no previously-included files found matching 'codecov.yml'
      warning: no previously-included files found matching 'renovate.json'
      warning: no previously-included files matching '.git*' found anywhere in distribution
      warning: no previously-included files matching '*.so' found anywhere in distribution
      no previously-included directories found matching '.ci'
      no previously-included directories found matching 'wheels'
      adding license file 'LICENSE'
      writing manifest file 'src/Pillow.egg-info/SOURCES.txt'
      running build_ext
      
      
      The headers or library files could not be found for zlib,
      a required dependency when compiling Pillow from source.
      
      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html
      
      Traceback (most recent call last):
        File "<string>", line 988, in <module>
        File "/tmp/pip-build-env-pam68rrj/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-pam68rrj/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-pam68rrj/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-pam68rrj/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-pam68rrj/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-pam68rrj/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-pam68rrj/normal/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 369, in run
          self.run_command("build")
        File "/tmp/pip-build-env-pam68rrj/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-pam68rrj/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-pam68rrj/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-pam68rrj/overlay/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/tmp/pip-build-env-pam68rrj/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-pam68rrj/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-pam68rrj/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-pam68rrj/overlay/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 88, in run
          _build_ext.run(self)
        File "/tmp/pip-build-env-pam68rrj/overlay/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "<string>", line 811, in build_extensions
      __main__.RequiredDependencyException: zlib
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/usr/local/lib/python3.9/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/local/lib/python3.9/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/local/lib/python3.9/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/tmp/pip-install-fsvrcghf/pillow_57d21ed3d7f94e208bd06b7fd1e942b6/_custom_build/backend.py", line 53, in build_wheel
          return super().build_wheel(wheel_directory, config_settings, metadata_directory)
        File "/tmp/pip-build-env-pam68rrj/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 434, in build_wheel
          return self._build_with_temp_dir(
        File "/tmp/pip-build-env-pam68rrj/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 419, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-install-fsvrcghf/pillow_57d21ed3d7f94e208bd06b7fd1e942b6/_custom_build/backend.py", line 47, in run_setup
          return super().run_setup(setup_script)
        File "/tmp/pip-build-env-pam68rrj/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 1005, in <module>
      __main__.RequiredDependencyException:
      
      The headers or library files could not be found for zlib,
      a required dependency when compiling Pillow from source.
      
      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html
      
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for Pillow
Failed to build Pillow
ERROR: Could not build wheels for Pillow, which is required to install pyproject.toml-based projects

**Comment by gitstq** [comment]
root@onecloud:~# python3 -V
Python 3.9.2
root@onecloud:~# pip -V
pip 23.3.1 from /usr/local/lib/python3.9/dist-packages/pip (python 3.9)

**Comment by gitstq** [comment]
python3 -V
Python 3.9.2
 pip -V
pip 23.3.1 from /usr/local/lib/python3.9/dist-packages/pip (python 3.9)

**Comment by lemisky** [comment]
![Screenshot_20231105-135729__01.jpg](https://github.com/foyoux/aligo/assets/35125624/23529e8f-d8e4-4e49-9f53-6cf31243e83b)
