### ISSUE TITLE
好像只能秒传了，之前没这问题

### ISSUE THREAD

**Issue by 1059841705** [foyoux/aligo#32]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1012, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fc314b64b80>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Max retries exceeded with url: /adrive/v3/file/list (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc314b64b80>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/upload.py", line 6, in <module>
    remote_folder = ali.get_folder_by_path('download')
  File "/usr/local/lib/python3.9/dist-packages/aligo/apis/File.py", line 158, in get_folder_by_path
    folders = self.get_file_list(parent_file_id=parent_file_id, drive_id=drive_id, type='folder')
  File "/usr/local/lib/python3.9/dist-packages/aligo/apis/File.py", line 97, in get_file_list
    return list(result)
  File "/usr/local/lib/python3.9/dist-packages/aligo/core/File.py", line 16, in _core_get_file_list
    yield from self._list_file(ADRIVE_V3_FILE_LIST, body, GetFileListResponse)
  File "/usr/local/lib/python3.9/dist-packages/aligo/core/BaseAligo.py", line 161, in _list_file
    response = self._post(PATH, body=body)
  File "/usr/local/lib/python3.9/dist-packages/aligo/core/BaseAligo.py", line 93, in _post
    return self._auth.post(path=path, host=host, body=body, ignore_auth=ignore_auth)
  File "/usr/local/lib/python3.9/dist-packages/aligo/core/Auth.py", line 350, in post
    return self.request(method='POST', url=host + path, params=params,
  File "/usr/local/lib/python3.9/dist-packages/aligo/core/Auth.py", line 300, in request
    response = self.session.request(
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Max retries exceeded with url: /adrive/v3/file/list (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc314b64b80>: Failed to establish a new connection: [Errno 110] Connection timed out'))

**Comment by lemisky** [comment]
这是网络问题

**Comment by 1059841705** [comment]
> 是不是开了代码啥的？

两个小时前上传一半断了
再传就几百kb/s
是不是触发了什么

**Comment by lemisky** [comment]
这个很正常，我用官方客户端下，也会这样。

**Comment by lemisky** [comment]
没有靠谱解决方案
